// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

// eslint-disable-next-line @typescript-eslint/consistent-type-definitions
interface CloudflareEnv {
  CRON_USERNAME: string;
  CRON_PASSWORD: string;
  TURSO_DATABASE_URL: string;
  TURSO_AUTH_TOKEN: string;
}
